spring:
  redis:
    host: localhost
    port: 6379
    password: 'whystay'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    h2:
#      console:
#        enabled: true
#        path: /h2
#        settings:
#          web-allow-others: true
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/main_project?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
  #    username: whystay
  #    password: 1234
  datasource:
    url: jdbc:mysql://whystay-mysql.czwot3oq2gjk.ap-northeast-2.rds.amazonaws.com:3306/mainproject_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: whystay1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      data-locations: classpath*:db/h2/data.sql
jwt:
  key: ${JWT_SECRET_KEY}
  refresh-token-expiration-minutes: 420
  access-token-expiration-minutes: 360
mail:
  address:
    admin: admin@gmail.com

#KakaoPay
kakao:
  admin:
    key: 7d8b34bddd92b4d25454fe47608e39ab
  host: http://localhost:8080

config:
  domain: http://whystay-mysql.czwot3oq2gjk.ap-northeast-2.rds.amazonaws.com